services:
  app-mongodb-dev:
    image: app-mongodb-dev
    container_name: app-mongodb-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
      - .env.development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    command: yarn start